site_name: Teste

plugins:
   - swagger-ui-tag

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


theme:
  name: 'material'
  language: 'pt'
  logo: ''
  favicon: ''
  palette:
    primary: 'Blue'
    accent: 'light blue'
  font:
    text: 'Montserrat'
    code: 'sans-serif'
    features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.indexes
      - toc.follow
      - content.code.annotate

nav:
  - Home: index.md
